checkpoint_dir = "checkpoints"
init_model_path = "../inits/csm-1b-expresso"
num_epochs = 5

[wandb]
project_name = "csm_expresso"
use_wandb = true

[optim]
betas = [0.9, 0.95]
lr = 5e-4
accumulate_steps = 3

[dataset]
num_workers = 12
batch_size = 12
dataset_dir = "../datasets/tokenized_expresso"
p_amortize_keep_alive = 0.0625
