checkpoint_dir = "checkpoints"

[wandb]
project_name = "csm_decoder_shortcut"
use_wandb = false

[optim]
betas = [0.9, 0.95]
lr = 3e-4

[dataset]
num_workers = 12
batch_size = 8
dataset_dir = "../datasets/tokenized_libritts"
p_amortize_keep_alive = 0.0625
